[package]
name = "node"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = { version = "1.10.1" }
futures = { version = "0.3.31" }
prost = "0.13.5"
prost-derive = "0.13.5"
tokio = { version = "1.45.1", features = ["full"] }